#!/bin/bash -e

toolsdir=$(cd `dirname $0`; pwd)
cd $toolsdir/..

# Fix TypographyEllipsis programmatically
sed -i 's/\.\.\./…/g' app/src/main/res/values*/strings.xml

# Replace "--" with an "em dash" character
sed -i 's,\(\>[^\<]*\)--\([^\>]\),\1—\2,g' app/src/main/res/values*/strings.xml

# indent <string> lines like Android Studio does
sed -i "s,^\s*<string,    <string," app/src/main/res/values*/strings.xml

# no indent on <resources>
sed -i 's,\s*<resources>,<resources>,' app/src/main/res/values*/strings.xml
sed -i 's,\s*</resources>,</resources>,' app/src/main/res/values*/strings.xml

# strip leading whitespace
sed -Ei 's,(<string[^>]+>)\s*,\1,' app/src/main/res/values*/strings.xml

# strip trailing whitespace
sed -i 's,\s*</string>,</string>,' app/src/main/res/values*/strings.xml

$toolsdir/check-fastlane-whitespace.py

if ! git diff --exit-code > /dev/null; then
    echo "Run fix-translations and include the needed differences!"
    exit 1
fi
